"""empty message

Revision ID: 1327d32301e1
Revises: 24aed7c758f1
Create Date: 2019-09-05 19:29:26.953274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1327d32301e1'
down_revision = '24aed7c758f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.String(), nullable=False))
    op.add_column('book', sa.Column('genre', sa.String(), nullable=False))
    op.add_column('book', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'status')
    op.drop_column('book', 'genre')
    op.drop_column('book', 'author')
    # ### end Alembic commands ###
